"""Vue 3 SFC (Single File Component) generator for FigmaForge.

Generates Vue 3 components with Composition API, TypeScript,
and scoped styles from Figma designs.
"""

from typing import Dict, Any, List, Optional
from pathlib import Path
from ..figma.types import FigmaNode
from ..utils.css import sanitize_css_class, to_camel_case, to_pascal_case


class VueGenerator:
    """Generates Vue 3 Single File Components from Figma designs.
    
    Produces a single .vue file containing:
    - <template> - HTML template
    - <script setup lang="ts"> - Composition API with TypeScript
    - <style scoped> - Scoped CSS styles
    """
    
    def __init__(
        self, 
        component_name: str,
        variant_inputs: Optional[List[Dict[str, Any]]] = None
    ):
        self.component_name = component_name
        self.class_name = to_pascal_case(component_name)
        self.variant_inputs = variant_inputs or []
        self.asset_paths: Dict[str, str] = {}
        self.inline_svgs: Dict[str, str] = {}
        self.template_elements: List[str] = []
    
    def generate_component(
        self,
        node: FigmaNode,
        asset_paths: Optional[Dict[str, str]] = None,
        inline_svgs: Optional[Dict[str, str]] = None
    ) -> Dict[str, str]:
        """Generate Vue SFC content.
        
        Returns:
            Dict with 'vue' key containing the SFC content
        """
        self.asset_paths = asset_paths or {}
        self.inline_svgs = inline_svgs or {}
        self.template_elements = []
        
        # Collect template elements
        self._collect_template_elements(node)
        
        vue_content = self._generate_sfc(node)
        
        return {
            "vue": vue_content
        }
    
    def _generate_sfc(self, node: FigmaNode) -> str:
        """Generate the complete Vue SFC."""
        template = self._generate_template()
        script = self._generate_script()
        style = self._generate_style()
        
        return f"""<!-- Auto-generated by FigmaForge -->
<template>
{template}
</template>

<script setup lang="ts">
{script}
</script>

<style scoped>
{style}
</style>
"""
    
    def _generate_template(self) -> str:
        """Generate Vue template section."""
        lines = [
            f'  <div class="{self.component_name}">'
        ]
        
        for element in self.template_elements:
            lines.append(f"    {element}")
        
        lines.append("    <slot></slot>")
        lines.append("  </div>")
        
        return "\n".join(lines)
    
    def _generate_script(self) -> str:
        """Generate Vue script section with Composition API."""
        lines = [
            "// ==================== AUTO-GEN-START ====================",
            "",
        ]
        
        # Define props
        if self.variant_inputs:
            lines.append("interface Props {")
            for inp in self.variant_inputs:
                name = inp.get("name", "")
                ts_type = inp.get("type", "string")
                lines.append(f"  {name}?: {ts_type};")
            lines.append("}")
            lines.append("")
            
            # Use withDefaults for props with defaults
            defaults = ", ".join([
                f"{inp['name']}: '{inp['default']}'" 
                for inp in self.variant_inputs
            ])
            lines.append(f"const props = withDefaults(defineProps<Props>(), {{")
            lines.append(f"  {defaults}")
            lines.append("});")
        else:
            lines.append("// No props defined")
        
        lines.append("")
        lines.append("// ==================== AUTO-GEN-END ====================")
        
        return "\n".join(lines)
    
    def _generate_style(self) -> str:
        """Generate scoped CSS styles."""
        lines = [
            "/* ==================== AUTO-GEN-START ==================== */",
            "",
            f".{self.component_name} {{",
            "  position: relative;",
            "  width: 100%;",
            "}",
            "",
            "/* ==================== AUTO-GEN-END ==================== */",
        ]
        
        return "\n".join(lines)
    
    def _collect_template_elements(self, node: FigmaNode) -> None:
        """Recursively collect template elements."""
        node_type = node.get("type", "")
        
        if node_type in ["DOCUMENT", "CANVAS"]:
            for child in node.get("children", []):
                if isinstance(child, dict):
                    self._collect_template_elements(child)
            return
        
        for child in node.get("children", []):
            if isinstance(child, dict) and child.get("visible", True):
                element = self._generate_element(child)
                if element:
                    self.template_elements.append(element)
                self._collect_template_elements(child)
    
    def _generate_element(self, node: FigmaNode) -> str:
        """Generate Vue template element."""
        node_type = node.get("type", "")
        class_name = self._generate_class_name(node)
        
        if node_type == "TEXT":
            text = node.get("characters", "")
            if text:
                escaped = text.replace("<", "&lt;").replace(">", "&gt;")
                return f'<span class="{class_name}">{escaped}</span>'
            return f'<span class="{class_name}">{{{{ text }}}}</span>'
        
        elif node_type in ["RECTANGLE", "ELLIPSE", "VECTOR"]:
            node_id = node.get("id", "")
            if node_id in self.inline_svgs:
                svg = self.inline_svgs[node_id]
                return f'<span class="{class_name}" v-html="`{svg}`"></span>'
            elif node_id in self.asset_paths:
                path = self.asset_paths[node_id]
                return f'<img :src="`{path}`" alt="" class="{class_name}" />'
        
        return f'<div class="{class_name}"></div>'
    
    def _generate_class_name(self, node: FigmaNode) -> str:
        """Generate CSS class name."""
        name = node.get("name", "element")
        return sanitize_css_class(name)
